# CI config

# shared key for the python jobs to not have redundant config parameters
# PROJECT, TESTSDIR, SRCDIR are used in the tox.ini
.python_defaults: &py_anchor  # using anchor magic
    image: registry.gitlab.semanticlab.net/docker/py3base:latest 
    before_script:
        - git submodule sync --recursive
        - git submodule update --init --recursive --remote
        - cp wl_python_utils/python3/* .
        - sed -i s/-dev//g setup.py
        - export PROJECT=$(/usr/bin/python3 -W ignore ./setup.py --name | awk 'NR==1{print $1}')
        - export VERSION=$(/usr/bin/python3 -W ignore ./setup.py --version | awk 'NR==1{print $1}')
        - export TESTSDIR=src/python/weblyzard_api/tests/model/
        - export SRCDIR=src/python/weblyzard_api/
    only:
        - migration
    tags: 
        - docker
    
stages:
    - test-python
      #    - test-java
    - build-package

pytest:
    <<: *py_anchor  # we reference the anchor here
    stage: test-python
    script:
        - tox -e pytest
        - sonar-scanner -D sonar.host.url=$sonarhost -D sonar.login=$sonarlogin

pylint:
    <<: *py_anchor
    stage: test-python
    script:
        - tox -e pylint
    when: manual

vulture:
    <<: *py_anchor
    stage: test-python
    script:
        - tox -e vulture
    when: manual
    
# the sed and exports needed are in the actual build-package.sh
build:
    stage: build-package
    script:
        - chmod +x build-package.sh
        - ./build-package.sh
    only:
        - migration
    when: manual
    tags:
        - shell-runner
