dist: xenial
language: java

git:
    submodules: false

jdk:
  - openjdk11

test: echo "Skipping test stage, using scripts to perform unit tests and quality metrics."

script:
    mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -DskipITs -Dgpg.skip=true -Dmaven.test.failure.ignore=false sonar:sonar -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST
    cd java-examples/keyword-extraction; mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -DskipITs -Dgpg.skip=true -Dmaven.test.failure.ignore=false sonar:sonar -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST

cache:
  directories:
  - $HOME/.m2

